INSERT INTO yourmovies.t_actors(country,f_born,name) VALUES ('Estados Unidos','1994-03-14','Ansel Elgort');
INSERT INTO yourmovies.t_actors(country,f_born,name) VALUES ('Estados Unidos','1991-11-15','Shailene Diann Woodley');
INSERT INTO yourmovies.t_actors(country,f_born,name) VALUES ('Estados Unidos','1958-10-20','Viggo Peter Mortensen');
INSERT INTO yourmovies.t_actors(country,f_born,name) VALUES ('Inglaterra','1939-05-25','Ian Murray McKellen');
INSERT INTO yourmovies.t_actors(country,f_born,name) VALUES ('Estados Unidos','1981-01-28','Elijah Jordan Wood');
INSERT INTO yourmovies.t_actors(country,f_born,name) VALUES ('Inglaterra','1975-10-05','Kate Elizabeth Winslet');
INSERT INTO yourmovies.t_actors(country,f_born,name) VALUES ('Estados Unidos','1974-11-11','Leonardo DiCaprio');

INSERT INTO yourmovies.t_movies(anno,direccion,duracion,genero,imagen,pais,sinopsis,titulo)VALUES(1997,'James Cameron',180,'Drama','33a47d24-e17b-4c23-961c-e73a82afe05f_titanic.jpg','Estados Unidos','Titanic es una película estadounidense dramática de catástrofe de 1997 dirigida y escrita por James Cameron y protagonizada por Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates, Gloria Stuart y Bill Paxton. La trama, una epopeya romántica, relata la relación de Jack Dawson y Rose DeWitt Bukater, dos jóvenes que se conocen y se enamoran a bordo del transatlántico RMS Titanic en su viaje inaugural desde Southampton (Inglaterra) a Nueva York (EE. UU.) en abril de 1912. Pertenecientes a diferentes clases sociales, intentan salir adelante pese a las adversidades que los separarían de forma definitiva, entre ellas el prometido de Rose, Caledon «Cal» Hockley (un adinerado del cual ella no está enamorada, pero su madre la ha obligado a permanecer con él para garantizar un futuro económico próspero) y el hundimiento del barco tras chocar con un iceberg.','Titanic');
INSERT INTO yourmovies.t_movies(anno,direccion,duracion,genero,imagen,pais,sinopsis,titulo)VALUES(2001,'James Cameron',180,'Aventura','cf18b70d-b127-475b-a9eb-fe1ce37464fc_tsdla.jpg','Nueva Zelanda','Ambientada en la Tierra Media, cuenta la historia del Señor Oscuro Sauron, que está buscando el Anillo Único, el cual ha acabado en poder del hobbit Frodo Bolsón (Elijah Wood). El destino de la Tierra Media está en juego mientras Frodo y ocho compañeros que forman la Compañía del Anillo comienzan un largo y peligroso viaje hacia el Monte del Destino en la tierra de Mordor, que es el único lugar en el que el anillo puede ser destruido.','El Señor de los Anillos: la Comunidad del Anillo');
INSERT INTO yourmovies.t_movies(anno,direccion,duracion,genero,imagen,pais,sinopsis,titulo)VALUES(2014,'Josh Boone',123,'Drama','2c911777-844e-498a-b840-1ff6429e36c7_blme.jpg','Estados Unidos','Hazel Grace Lancaster (Shailene Woodley) es una adolescente que vive en los suburbios de Indianápolis, ella sufre de cáncer de tiroides en etapa terminal que ha hecho metástasis en sus pulmones. Creyendo que está deprimida, su madre Frannie (Laura Dern) le pide asistir a un grupo de apoyo semanal para pacientes con cáncer para ayudarla a hacer amigos con personas que están pasando por lo mismo. Allí, Hazel conoce a Augustus "Gus" Waters (Ansel Elgort), un encantador adolescente que perdió una pierna por un cáncer de hueso pero desde entonces aparentemente no ha tenido cáncer. Invita a Hazel a su casa donde se unen por sus pasatiempos y aceptan leer los libros favoritos de cada uno. Hazel le recomienda a Gus Un Dolor Imperial, una novela sobre una niña enferma de cáncer llamada Anna que es paralela a su experiencia, y Gus le da a Hazel, la nóvela sobre su videojuego favorito "Contra Insurgencia". Se mantienen en contacto por mensaje de texto durante las semanas siguientes y se vuelven más cercanos. Después de','Bajo la misma estrella');

INSERT INTO yourmovies.t_movies_actors(movie_id,actor_id)VALUES(1,7);
INSERT INTO yourmovies.t_movies_actors(movie_id,actor_id)VALUES(1,6);
INSERT INTO yourmovies.t_movies_actors(movie_id,actor_id)VALUES(2,5);
INSERT INTO yourmovies.t_movies_actors(movie_id,actor_id)VALUES(2,4);
INSERT INTO yourmovies.t_movies_actors(movie_id,actor_id)VALUES(2,3);
INSERT INTO yourmovies.t_movies_actors(movie_id,actor_id)VALUES(3,2);
INSERT INTO yourmovies.t_movies_actors(movie_id,actor_id)VALUES(3,1);